name: react-app
on:
    push:
        branches:
         - master

jobs:
    build:
        runs-on: ubuntu-Latest
        steps:
        - name: Install Node
          uses: actions/setup-node@v3
          with:
            node version: 18

        - name: Checkout Our Repo
          uses: actions/checkout@v3
          with:
            ref: master

        - name: Build This App
          run: |
            npm install
            npm run build
        - name: Deploy On Ec2
          run: |
            ls -al build/
            mkdir ip ~/.ssh && touch ~/.ssh/known_hosts
            ssh-keyscan -t rsa ec2-34-224-223-235.compute-1.amazonaws.com >> ~/.ssh/known_hosts
            chmod 400 cicdpipeline.pem
            scp -i "cicdpipeline.pem" build/ ubuntu@ec2-34-224-223-235.compute-1.amazonaws.com:/var/www.html
